training_config:
  project_name: final_cifar_fedlaw_backdoor
  model_name: DeeperCIFARCNN
  aggregate_type: sparse
  dataset_name: CIFAR10
  num_clients: 200
  fraction_malicious: 0.4
  total_epochs: 400
  q_factor: 0.8
  evaluate_each_epoch: 1
  attack_args:
    attack_type: backdoor
    attack_epoch: 2
    backdoor_pattern:
      i: 9
      j: 9
      h: 10
      w: 10
      v: [0, 0, 0]
    backdoor_target: random
    max_label: 9
  normalize_params: false
  batch_size: 16
  local_epochs: 3
  malicious_type: group_oriented
  sparse_params:
    alpha: 0.01
    beta: 0.0001
    is_ftotal: true
    k_value:
    - 8
    - 50
    - null
    - null
    - null
    - 0.05
    c_alpha: 0.0001
    rho_alpha: 0.5
    max_line_search_iterations_alpha: 0
    c_beta: 0.0001
    rho_beta: 0.5
    max_line_search_iterations_beta: 0
sweep_config:
  method: grid
  metric:
    name: test_accuracy
    goal: maximize
  parameters:
    q_factor:
      values:
      - 0.9
      - 0.6
    fraction_malicious:
      values:
      - 0.4
      - 0.3
      - 0.2
      - 0.1
    sparse_params.alpha:
      values:
      - 0.01
    sparse_params.beta:
      values:
      - 0.0006
      - 0.0003
