training_config:
  project_name: final_mnist_sparse_weights
  model_name: ThreeLayerFC
  aggregate_type: sparse
  dataset_name: MNIST
  num_clients: 10
  fraction_malicious: 0.4
  total_epochs: 200
  q_factor: 0.8
  evaluate_each_epoch: 1
  attack_args:
    attack_type: backdoor
    attack_epoch: 2
    backdoor_pattern:
      i: 9
      j: 9
      h: 10
      w: 10
      v: 0
    backdoor_target: random
    max_label: 9
  batch_size: 64
  local_epochs: 3
  malicious_type: group_oriented
  sparse_params:
    alpha: 0.01
    beta: 0.0001
    is_ftotal: true
    k_value:
    - 10
    - 20
    - null
    - null
    - 0.009
    c_alpha: 0.0001
    rho_alpha: 0.5
    max_line_search_iterations_alpha: 0
    c_beta: 0.0001
    rho_beta: 0.5
    max_line_search_iterations_beta: 0
sweep_config:
  method: grid
  metric:
    name: test_accuracy
    goal: maximize
  parameters:
    q_factor:
      values:
      - 0.9
    fraction_malicious:
      values:
      - 0.4
    sparse_params.alpha:
      values:
      - 0.01
    sparse_params.beta:
      values:
      - 0.0015
      - 0.0006
    sparse_params.k_value:
      values:
      - - 0
        - 10
        - null
        - null
        - null
        - 0.05
      - - 8
        - 100
        - null
        - null
        - null
        - 0.05
    normalize_params:
      values:
      - false