training_config:
  project_name: final_cifar_sparse_flip_labels
  model_name: DeeperCIFARCNN
  aggregate_type: sparse
  dataset_name: CIFAR10
  num_clients: 200
  fraction_malicious: 0.4
  total_epochs: 400
  q_factor: 0.8
  evaluate_each_epoch: 1
  attack_args:
    attack_type: flip_labels
    attack_epoch: 2
    max_label: 9
  batch_size: 64
  local_epochs: 3
  malicious_type: group_oriented
  sparse_params:
    alpha: 0.01
    beta: 0.0001
    is_ftotal: true
    lambda_val:
    - 0
    - 0.0025
    - 100
    c_alpha: 0.0001
    rho_alpha: 0.5
    max_line_search_iterations_alpha: 0
    c_beta: 0.0001
    rho_beta: 0.5
    max_line_search_iterations_beta: 0
sweep_config:
  method: grid
  metric:
    name: test_accuracy
    goal: maximize
  parameters:
    q_factor:
      values:
      - 0.8
      - 0.7
    fraction_malicious:
      values:
      - 0.3
      - 0.2
      - 0.1
      - 0.05
    sparse_params.alpha:
      values:
      - 0.01
    sparse_params.beta:
      values:
      - 0.0016
      - 0.0008
      - 0.0005
    sparse_params.lambda_val:
      values:
      - - 0
        - 0.0025
        - 15
    sparse_params.max_line_search_iterations_beta:
      values:
      - 0
