training_config:
  project_name: final_cifar_rfa_bucketing_double_attack_fixed
  model_name: DeeperCIFARCNN
  aggregate_type: fedavg
  dataset_name: CIFAR10
  num_clients: 200
  fraction_malicious: 0.4
  total_epochs: 400
  q_factor: 0.8
  evaluate_each_epoch: 1
  multi_attack_args:
    - attack_type: boost_gradient
      attack_epoch: 2
      boost_factor: -1
      fraction_malicious: 0.5
    - attack_type: random_parameters
      attack_epoch: 5
      random_parameters_mean: 5
      random_parameters_std: 1.5
      fraction_malicious: 0.5
  defence_args:
    defence_type: rfa_bucketing
    bucketing_factor: 2
    rfa_nu: 1e-6
    rfa_R: 3
    rfa_init: mean
  batch_size: 16
  local_epochs: 3
  malicious_type: group_oriented
  fedavg_params:
    alpha: 0.01
sweep_config:
  method: grid
  metric:
    name: test_accuracy
    goal: maximize
  parameters:
    q_factor:
      values:
      - 0.9
      - 0.6
    fraction_malicious:
      values:
      - 0.4
      - 0.3
      - 0.2
      - 0.1
    fedavg_params.alpha:
      values:
      - 0.01
    defence_args.bucketing_factor:
      values:
      - 2
