training_config:
  project_name: final_mnist_sparse_double_attack
  model_name: ThreeLayerFC
  aggregate_type: sparse
  dataset_name: MNIST
  num_clients: 200
  fraction_malicious: 0.4
  total_epochs: 200
  q_factor: 0.8
  evaluate_each_epoch: 1
  multi_attack_args:
    - attack_type: boost_gradient
      attack_epoch: 5
      boost_factor: -1
      fraction_malicious: 0.5
    - attack_type: random_parameters
      attack_epoch: 2
      random_parameters_mean: 5
      random_parameters_std: 1.5
      fraction_malicious: 0.5
  batch_size: 64
  local_epochs: 3
  malicious_type: group_oriented
  sparse_params:
    alpha: 0.01
    beta: 0.0001
    is_ftotal: true
    lambda_val:
    - 0
    - 0.0025
    - 100
    c_alpha: 0.0001
    rho_alpha: 0.5
    max_line_search_iterations_alpha: 0
    c_beta: 0.0001
    rho_beta: 0.5
    max_line_search_iterations_beta: 0
sweep_config:
  method: grid
  metric:
    name: test_accuracy
    goal: maximize
  parameters:
    q_factor:
      values:
      - 0.9
      - 0.6
    fraction_malicious:
      values:
      - 0.4
      - 0.3
      - 0.2
      - 0.1
    sparse_params.alpha:
      values:
      - 0.01
    sparse_params.beta:
      values:
      - 0.002
      - 0.0015
      - 0.001
      - 0.0005
    sparse_params.lambda_val:
      values:
      - - 0
        - 0.0025
        - 20
    sparse_params.max_line_search_iterations_beta:
      values:
      - 0
