training_config:
  project_name: final_mnist_bulyan_double_attack
  model_name: ThreeLayerFC
  aggregate_type: fedavg
  dataset_name: MNIST
  num_clients: 200
  fraction_malicious: 0.4
  total_epochs: 200
  q_factor: 0.8
  evaluate_each_epoch: 1
  multi_attack_args:
    - attack_type: boost_gradient
      attack_epoch: 2
      boost_factor: -1
      fraction_malicious: 0.5
    - attack_type: random_parameters
      attack_epoch: 5
      random_parameters_mean: 5
      random_parameters_std: 1.5
      fraction_malicious: 0.5
  defence_args:
    defence_type: bulyan
    bulyan_factor: 25
    krum_factor: 170
  batch_size: 64
  local_epochs: 3
  malicious_type: group_oriented
  fedavg_params:
    alpha: 0.01
sweep_config:
  method: grid
  metric:
    name: test_accuracy
    goal: maximize
  parameters:
    q_factor:
      values:
      - 0.9
      - 0.6
    fraction_malicious:
      values:
      - 0.4
      - 0.3
      - 0.2
      - 0.1
    fedavg_params.alpha:
      values:
      - 0.01
    defence_args.bulyan_factor:
      values:
      - 50
      - 40
      - 20
