training_config:
  project_name: final_cifar_bulyan_flip_labels
  model_name: DeeperCIFARCNN
  aggregate_type: fedavg
  dataset_name: CIFAR10
  num_clients: 200
  fraction_malicious: 0.4
  total_epochs: 400
  q_factor: 0.8
  evaluate_each_epoch: 1
  attack_args:
    attack_type: flip_labels
    attack_epoch: 2
    max_label: 9
  defence_args:
    defence_type: bulyan
    bulyan_factor: 25
    krum_factor: 170
  batch_size: 64
  local_epochs: 3
  malicious_type: group_oriented
  fedavg_params:
    alpha: 0.01
sweep_config:
  method: grid
  metric:
    name: test_accuracy
    goal: maximize
  parameters:
    q_factor:
      values:
      - 0.8
      - 0.7
    fraction_malicious:
      values:
      - 0.4
      - 0.3
      - 0.2
      - 0.1
    fedavg_params.alpha:
      values:
      - 0.01
    defence_args.bulyan_factor:
      values:
      - 50
